CREATE TABLE IF NOT EXISTS `Trails` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(30) NOT NULL,
	`description` VARCHAR(400) NOT NULL DEFAULT '',
	`city` VARCHAR(30) NOT NULL DEFAULT '',
	`region` VARCHAR(30) NOT NULL DEFAULT '',
	`country` VARCHAR(30) NOT NULL DEFAULT '',
	`coord` POINT NOT NULL,
	`length` FLOAT NOT NULL DEFAULT 0,
	`difficulty` VARCHAR(20) NOT NULL DEFAULT '',
	`features` VARCHAR(100) NOT NULL DEFAULT '',
	`rating` FLOAT NOT NULL DEFAULT 0,
	`thumbnail` VARCHAR(300) NOT NULL DEFAULT '',
	`api_id` INT NOT NULL DEFAULT 0,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
